# -*- coding: utf-8 -*-
"""ftdetect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5fuvFLlYAJDCJiXW_sbgmod34-1Muis
"""

!sudo apt -y install libportaudio2
!pip install -q pycocotools
!pip install -q opencv-python-headless==4.1.2.30
!pip uninstall -y tensorflow && pip install -q tensorflow==2.8.0

!pip install -q tflite_model_maker

import numpy as np
import os

from tflite_model_maker.config import ExportFormat, QuantizationConfig
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector

from tflite_support import metadata

import tensorflow as tf
assert tf.__version__.startswith('2')

tf.get_logger().setLevel('ERROR')
from absl import logging
logging.set_verbosity(logging.ERROR)

from google.colab import drive
drive.mount('/content/drive')

!unzip -q feet_pics.zip 
train_data = object_detector.DataLoader.from_pascal_voc(
    'feet_pics/train', 
    'feet_pics/train', 
    ['foot']
)
val_data = object_detector.DataLoader.from_pascal_voc(
    'feet_pics/val',
    'feet_pics/val', 
    ['foot']
)

spec = model_spec.get('efficientdet_lite0')
model = object_detector.create(train_data, model_spec=spec, batch_size=4, train_whole_model=True, epochs=20, validation_data=val_data)

model.evaluate(val_data)

model.export(export_dir='.', tflite_filename='android.tflite')

model.evaluate_tflite('android.tflite', val_data)